version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - config:/config
      - $DOCKER_STORAGE/jellyfin/cache:/cache
      - $DOCKER_STORAGE/jellyfin/media:/media
    restart: 'always'
    networks:
      - traefiknet
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.dockerbox.local
    group_add: # by id as these may not exist within the container. Needed to provide permissions to the VAAPI Devices
      - '104' #render
      - '44' #video
    devices:
    # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.dockerbox.local`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - 'traefik.http.services.jellyfin.loadBalancer.passHostHeader=true'
networks:
  traefiknet:
    external: true
volumes:
  config:
